sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t jw0401/docker-react -f Dockerfile.dev ./

script:
  - docker run -e CI=true jw0401/docker-react npm run test -- --coverage

after_success:
  - echo "test success"